# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luminose
email: florent@luminose.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.luminose.fr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed # possible values: nested expanded compact compressed

exclude: [
          "run.sh",
          "pack.sh",
          "Gemfile",
          "Gemfile.lock"
         ]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
