# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luminose
email: florent@luminose.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.luminose.fr" # the base hostname & protocol for your site
author: Florent Jaouali
logo: /images/luminose-logo.png
locale: fr_FR

# Build settings
markdown: kramdown
timezone: Europe/Paris
future: true

permalink: /blog/:categories/:title:output_ext

collections:
  evenements:
    output: true
    permalink: /:collection/:categories/:path:output_ext

sass:
  style: compressed # possible values: nested expanded compact compressed

exclude: [
          "run.sh",
          "Gemfile",
          "Gemfile.lock"
         ]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path:            "google76d39b4cffa5fbc0.html"
    values:
      sitemap:         false